### ISSUE TITLE
dependencies skipped while creating a database

### ISSUE THREAD

**Issue by hshenCode** [github/codeql-go#580]
I create a database for my repo with gomod, but all the dependencies are skipped, which result that, when I run a dataflow query, it can't detect the tainted actions and nodes in the library.

Is there any mistake in my creation or query?

logs:
[2021-10-11 12:22:22] [build-stderr] 2021/10/11 12:22:22 Skipping dependency package xx/gopkg/jsonx

**Comment by smowton** [comment]
I believe that message is expected -- it means we're skipping full code extraction from what appears to be library code, which is intentional in order to keep the scope of the analysis manageable. If you want to analyse the library itself, or the user code together with the library, then you could achieve this by altering the project layout to build the library and application code, with the library code outside the `vendor` directory.

**Comment by smowton** [comment]
If you're working with go.mod modules, this method worked for me (tested with github.com/kolide/fleet and its dependency github.com/kolide/kit)

1. Download the dependency repo to some directory within the main repo (I used 'fleet/kit')
2. Add a replace directive to the main go.mod: `replace replace github.com/kolide/kit => ./kit`
3. Run `go mod tidy` to update the main go.sum file to account for transitive dependencies
4. Run codeql database create --language=go from the root of the main project as usual

I haven't experimented with old non-module projects but your method sounds plausible for these.
